namespace: mariadb
mariadb:
  rootPassword: MariaDB11!
  password: MariaDB11!
maxscale:
  password: MaxScale11!
minio:
  accessKeyId: mariadb-operator
  secretAccessKey: Minio11!
  sessionToken: token
minioPlay:
  accessKeyId: Q3AM3UQ867SPQQA43P2F
  secretAccessKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  sessionToken: token

requests:
  cpu: 100m
  memory: 128Mi
limits:
  cpu: 500m
  memory: 1Gi

user:
  metadata:
    name: user

database:
  metadata:
    name: database

# backup:
#   resources:
#     requests:
#       cpu: 100m
#       memory: 128Mi
#     limits:
#       cpu: 300m
#       memory: 512Mi
