namespace: mariadb
mariadbpassword:
  password: MariaDB11!
  rootPassword: MariaDB11!
maxscale:
  password: MaxScale11!
minio:
  accessKeyId: mariadb-operator
  secretAccessKey: Minio11!
  sessionToken: token
minioPlay:
  accessKeyId: Q3AM3UQ867SPQQA43P2F
  secretAccessKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
  sessionToken: token

mariadb:
  database: mariadb
  storage:
    size: 1Gi
requests:
  cpu: 100m
  memory: 128Mi
limits:
  cpu: 500m
  memory: 1Gi
metrics:
  enabled: true

user:
  metadata:
    name: user

database:
  metadata:
    name: database

backup:
  schedule:
    cron: "*/1 * * * *"  # Modify this for your schedule
    suspend: false       # Change to true if you want to suspend the job
  timeZone: "UTC"         # Change to "Asia/Kolkata" for IST
  maxRetention: 720h      # 30 days retention
  compression: bzip2      # Compression format
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
