{{- if .Values.verticaBackup.cronJob.enabled }}
apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "{{ .Values.backup.schedule.cron }}"
    suspend: {{ .Values.backup.schedule.suspend }}
  timeZone: "{{ .Values.backup.timeZone }}"
  maxRetention: {{ .Values.backup.maxRetention }}
  compression: {{ .Values.backup.compression }}
  inheritMetadata:
    annotations:
      database.myorg.io: mariadb
  podMetadata:
    labels:
      sidecar.istio.io/inject: "false"
  serviceAccountName: backup
  storage:
    persistentVolumeClaim:
      resources:
        requests:
          storage: 100Mi
      accessModes:
        - ReadWriteOnce
  args:
    - --single-transaction
    - --all-databases
    - --verbose
  resources:
    requests:
      cpu: {{ .Values.backup.resources.requests.cpu }}
      memory: {{ .Values.backup.resources.requests.memory }}
    limits:
      cpu: {{ .Values.backup.resources.limits.cpu }}
      memory: {{ .Values.backup.resources.limits.memory }}
  affinity:
    antiAffinityEnabled: true
{{- end }}
