apiVersion: k8s.mariadb.com/v1alpha1
kind: Backup
metadata:
  name: backup-scheduled
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "*/1 * * * *"
    suspend: false
  timeZone: "UTC"
  maxRetention: 24h
  compression: bzip2
  storage:
    s3:
      bucket: backups
      endpoint: minio.minio.svc.cluster.local:9000
      accessKeyIdSecretKeyRef:
        name: minio
        key: mariadb-operator
      secretAccessKeySecretKeyRef:
        name: minio
        key: Minio11!
  args:
    - --single-transaction
    - --all-databases
  logLevel: info
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
