apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-root
    key: password
    generate: true

  username: mariadb
  passwordSecretKeyRef:
    name: mariadb-password
    key: password
    generate: true
  database: {{ .Values.mariadb.database }}

  port: 3306

  storage:
    size: {{ .Values.mariadb.storage.size }}

  service:
    type: NodePort
    # metadata:
    #   annotations:
    #     metallb.universe.tf/loadBalancerIPs: 172.18.0.20

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    innodb_buffer_pool_size=1024M
    max_allowed_packet=256M

  resources:
    requests:
      cpu: {{ .Values.requests.cpu }}
      memory: {{ .Values.requests.memory }}
    limits:
      cpu: {{ .Values.requests.cpu }}
      memory: {{ .Values.limits.memory }}

  metrics:
    enabled: {{ .Values.metrics.enabled }}
