apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: {{ .Values.namespace }}
  labels:
    k8s.mariadb.com/watch: ""
stringData:
  password: {{ .Values.mariadbpassword.password }}
  rootPassword: {{ .Values.mariadbpassword.rootPassword }}

---

apiVersion: v1
kind: Secret
metadata:
  name: maxscale
  namespace: {{ .Values.namespace }}
  labels:
    k8s.mariadb.com/watch: ""
stringData:
  password: {{ .Values.maxscale.password }}

---

apiVersion: v1
kind: Secret
metadata:
  name: minio
  namespace: {{ .Values.namespace }}
stringData:
  access-key-id: {{ .Values.minio.accessKeyId }}
  secret-access-key: {{ .Values.minio.secretAccessKey }}
  session-token: {{ .Values.minio.sessionToken }}

---

apiVersion: v1
kind: Secret
metadata:
  name: minio-play
  namespace: {{ .Values.namespace }}
stringData:
  access-key-id: {{ .Values.minioPlay.accessKeyId }}
  secret-access-key: {{ .Values.minioPlay.secretAccessKey }}
  session-token: {{ .Values.minioPlay.sessionToken }}
